openapi: "3.0.2"
info:
  title: API analyzer enade SI
  version: "1.0"
paths:
  /ies:
    get:
      tags:
        - /ies
      description: >-
        Get the IES list with code!
      responses:
        "200":
          description: Successful request.
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ies"
  /microdata:
    get:
      tags:
        - /microdata
      description: >-
        Get the Microdata rearranged!
      responses:
        "200":
          description: Successful request.
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/data_rearranged"
        default:
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

servers:
  - url: "/api"
components:
  schemas:
    ies:
      properties:
        cod_ies:
          type: integer
        sigla:
          type: string
        municipio:
          type: string
        uf:
          type: string
      required:
        - "sigla"
        - "cod_ies"
    data_rearranged:
      properties:
        cod_ies:
          type: integer
        sigla:
          type: string
        municipio:
          type: string
        uf:
          type: string
      required:
        - "sigla"
        - "cod_ies"
    Error:
      properties:
        message:
          type: string
      required:
        - message
