openapi: "3.0.2"
info:
  title: API analyzer enade SI
  version: "1.0"
paths:
  /ies:
    get:
      tags:
        - /ies
      description: >-
        Get the IES list with code!
      parameters:
        - in: query
          name: uf
          schema:
            type: string
        - in: query
          name: cod_ies
          schema:
            type: integer
      responses:
        "200":
          description: Successful request.
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ies"
  /questions-theme:
    get:
      tags:
        - /questions-theme
      description: >-
        Get the theme of questions!
      responses:
        "200":
          description: Successful request.
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: object
  /result-enade-general:
    get:
      tags:
        - /result-enade-general
      description: >-
        Get the general result of enade!
      parameters:
        - in: query
          name: uf
          schema:
            type: string
        - in: query
          name: cod_ies
          schema:
            type: integer
      responses:
        "200":
          description: Successful request.
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/general_data"
        default:
          description: Invalid request.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

servers:
  - url: "/api"
components:
  schemas:
    ies:
      properties:
        cod_ies:
          type: integer
        sigla:
          type: string
        municipio:
          type: string
        uf:
          type: string
      required:
        - "sigla"
        - "cod_ies"
    general_data:
      properties:
        total:
          type: integer
        result:
          type: array
          items:
            type:
              object
        tema:
          type: string
      required:
        - "tema"
        - "result"
    Error:
      properties:
        message:
          type: string
      required:
        - message
